micronaut:
  application:
    name: hejtobot

api:
  discord:
    key: ENC(3pCUpvPQWxp7mTi4dVB1jV+gY2pNizDwgl09g3B+0tzsXDKGrfb0DDWVlEC5IYgnURxNrOx07ZUaGGgaM+TA1MwAM8LMYXwgDbCFuFDj2vxJfIwBs6HsNFc5cOxWuwta)
  weather:
    key: ENC(OAXosKvEg5dk6bLjIVmoX3p0D6a3Wbo1P9GyZFKt4+enw4Tro8QYj6ti4SI766rvk/z3LL3OTSZxSeG/avk/0InlO0BzvNuM6Wkyci7v7zo=)