micronaut:
  application:
    name: hejtobot

api:
  discord:
    key: ENC(p2FO6g69Lr/hkmnKss41eXfWrE+caRqp68t6A1xCiXnPY/SFt9b1H4EbdueI/Y+zYWZI18frqnih9eJ48MulS41KzVHvy/F5UTm/52b6Rw04mB2MZ47c4pPJowo/VX0S)
  weather:
    key: ENC(4ZN1ey9MHoYfscsglzuSNz2KYA5VgBq5NfUg9x7nXgMNIPJzyf/Fd3ZNUYoMZEUfQRFv7sFS3hKJkZmdFSvxvssIQ4JEPb4sQy0KTn+7shQ=)